/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import static java.lang.String.valueOf;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static pagoimpuestovehicular.Principal_frame.lista_vehiculos;
import static pagoimpuestovehicular.Principal_frame.descProntoPago;
import static pagoimpuestovehicular.Principal_frame.descServPublico;
import static pagoimpuestovehicular.Principal_frame.descTrasCuenta;
import pagoimpuestovehicular.Vehiculo;


/**
 *
 * @author camil
 */
public class Admin_frame extends javax.swing.JFrame {
    public ArrayList<Vehiculo>vehiculos_disponibles = new ArrayList();
    /**
     * Creates new form Admin_frame
     */
    
    
    public Admin_frame() {
        initComponents();
        setSize(850, 600);
        setResizable(false);
        setLocationRelativeTo(this);
        
        
        input_marca.addItemListener( new ItemListener(){

            @Override
            public void itemStateChanged(ItemEvent e) {
                if ( e.getStateChange() == ItemEvent.SELECTED ) 
                {
                    String seleccion = valueOf(input_marca.getSelectedItem());
                    input_linea.removeAllItems();
                    String linea_a = "las"; 
                    for (int i=0; i<vehiculos_disponibles.size(); i++) {
                        if(seleccion.equals(vehiculos_disponibles.get(i).getMarca())){
                             if (linea_a != vehiculos_disponibles.get(i).getLinea()) {
                                 input_linea.addItem(vehiculos_disponibles.get(i).getLinea());
                                 linea_a = vehiculos_disponibles.get(i).getLinea();
                            }
                        }  
                    }
                }
            }
        });
        
        input_linea.addItemListener( new ItemListener(){

            @Override
            public void itemStateChanged(ItemEvent e) {
                if ( e.getStateChange() == ItemEvent.SELECTED ) 
                {
                    String seleccion = valueOf(input_linea.getSelectedItem());
                    input_agnio.removeAllItems();
                    String linea_a = "las"; 
                    for (int i=0; i<vehiculos_disponibles.size(); i++) {
                        if(seleccion.equals(vehiculos_disponibles.get(i).getLinea())){
                             if (linea_a != vehiculos_disponibles.get(i).getAgnio()) {
                                 input_agnio.addItem(vehiculos_disponibles.get(i).getAgnio());
                                 linea_a = vehiculos_disponibles.get(i).getAgnio();
                            }
                        }            
                    }
                }
            }
        });
        
        input_agnio.addItemListener( new ItemListener(){

            @Override
            public void itemStateChanged(ItemEvent e) {
                if ( e.getStateChange() == ItemEvent.SELECTED ) 
                {
                    String seleccion = valueOf(input_agnio.getSelectedItem());
                    for (int i=0; i<vehiculos_disponibles.size(); i++) {
                        if (seleccion.equals(vehiculos_disponibles.get(i).getAgnio())) {
                            input_valor.setText(valueOf(vehiculos_disponibles.get(i).getValorI()));
                        }
                    }
                }
            }
        });

        
        
        
        panel_desc.setVisible(false);
        descPPL.setText(valueOf(descProntoPago));
        descSPL.setText(valueOf(descServPublico));
        descTCL.setText(valueOf(descTrasCuenta));
        mostrarTabla();
        rellenarAutosDisponibles();
        mostrarMarcasVehiculosComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_vehiculos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        input_codigo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        input_marca = new javax.swing.JComboBox<>();
        input_linea = new javax.swing.JComboBox<>();
        input_agnio = new javax.swing.JComboBox<>();
        input_valor = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        descTCL = new javax.swing.JLabel();
        descPPL = new javax.swing.JLabel();
        descSPL = new javax.swing.JLabel();
        btn_panel_cambiar_desc = new javax.swing.JButton();
        panel_desc = new javax.swing.JPanel();
        input_descPP = new javax.swing.JTextField();
        input_descSP = new javax.swing.JTextField();
        input_descTC = new javax.swing.JTextField();
        btn_cambiar_desc = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        table_vehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Marca", "Línea", "Año", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_vehiculos.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(table_vehiculos);
        table_vehiculos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(28, 39, 529, 326);

        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Agregar Auto");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(80, 20, 110, 24);

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Valor:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 230, 60, 24);

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Código: ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 70, 60, 24);

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Marca:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 110, 60, 24);

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Línea:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 150, 60, 24);

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Año:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 190, 60, 24);
        jPanel2.add(input_codigo);
        input_codigo.setBounds(100, 70, 140, 24);

        jButton1.setText("Agregar auto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(100, 280, 140, 24);

        input_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_marcaActionPerformed(evt);
            }
        });
        jPanel2.add(input_marca);
        input_marca.setBounds(100, 110, 140, 26);

        jPanel2.add(input_linea);
        input_linea.setBounds(100, 150, 140, 26);

        jPanel2.add(input_agnio);
        input_agnio.setBounds(100, 190, 140, 26);
        jPanel2.add(input_valor);
        input_valor.setBounds(100, 230, 140, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(575, 39, 260, 326);

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Descuento por servicio público (%):");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(28, 454, 228, 24);

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Descuento por pronto pago (%): ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(28, 412, 209, 24);

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel9.setText("Descuento por traslado de cuenta (%):");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 490, 248, 24);

        descTCL.setText("jLabel10");
        getContentPane().add(descTCL);
        descTCL.setBounds(300, 490, 70, 16);

        descPPL.setText("jLabel10");
        getContentPane().add(descPPL);
        descPPL.setBounds(300, 410, 70, 16);

        descSPL.setText("jLabel10");
        getContentPane().add(descSPL);
        descSPL.setBounds(300, 450, 70, 16);

        btn_panel_cambiar_desc.setText("Cambiar valores");
        btn_panel_cambiar_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_panel_cambiar_descActionPerformed(evt);
            }
        });
        getContentPane().add(btn_panel_cambiar_desc);
        btn_panel_cambiar_desc.setBounds(380, 490, 140, 24);

        btn_cambiar_desc.setText("Cambiar");
        btn_cambiar_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cambiar_descActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_descLayout = new javax.swing.GroupLayout(panel_desc);
        panel_desc.setLayout(panel_descLayout);
        panel_descLayout.setHorizontalGroup(
            panel_descLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_descLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_descLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(input_descTC, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(input_descPP, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(input_descSP, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(31, 31, 31)
                .addComponent(btn_cambiar_desc, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_descLayout.setVerticalGroup(
            panel_descLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_descLayout.createSequentialGroup()
                .addComponent(input_descPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(input_descSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(input_descTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_descLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_cambiar_desc))
        );

        getContentPane().add(panel_desc);
        panel_desc.setBounds(550, 410, 230, 100);

        jLabel10.setText("Admin");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(680, 20, 48, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String marca, linea, agnio;
            int codigo;
            float valor;
            marca = valueOf(input_marca.getSelectedItem());
            linea = valueOf(input_linea.getSelectedItem());
            codigo = Integer.parseInt(input_codigo.getText());
            agnio = valueOf(input_agnio.getSelectedItem());
            valor = Float.parseFloat(input_valor.getText());

            if(!"".equals(marca)&&!"".equals(linea)&&!"".equals(codigo)&&!"".equals(agnio)&&!"".equals(valor)){
                Vehiculo vehiculo_aux = new Vehiculo();
                vehiculo_aux.setCodigo(codigo);
                vehiculo_aux.setMarca(marca);
                vehiculo_aux.setLinea(linea);
                vehiculo_aux.setValorI(valor);
                vehiculo_aux.setAgnio(agnio);
                
                lista_vehiculos.add(vehiculo_aux);
            }

        }catch(Exception e){}
        mostrarTabla();
        input_codigo.setText("");
        input_valor.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void input_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_marcaActionPerformed
        
    }//GEN-LAST:event_input_marcaActionPerformed

    private void input_agnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_agnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_agnioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_panel_cambiar_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_panel_cambiar_descActionPerformed
        panel_desc.setVisible(true);
        input_descPP.setText(valueOf(descProntoPago));  
        input_descSP.setText(valueOf(descServPublico));
        input_descTC.setText(valueOf(descTrasCuenta));
    }//GEN-LAST:event_btn_panel_cambiar_descActionPerformed

    private void btn_cambiar_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cambiar_descActionPerformed
       try {
            descProntoPago = Double.parseDouble(input_descPP.getText());
            descServPublico = Double.parseDouble(input_descSP.getText());
            descTrasCuenta = Double.parseDouble(input_descTC.getText());
            
            descPPL.setText(valueOf(descProntoPago));
            descSPL.setText(valueOf(descServPublico));
            descTCL.setText(valueOf(descTrasCuenta));
            
            panel_desc.setVisible(false);
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Introduzca el porcentaje a descontar.");
        }
      
    }//GEN-LAST:event_btn_cambiar_descActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_frame().setVisible(true);
            }
        });
    }
    //Funciones de frame
    
    public void mostrarTabla(){
        String matriz[][] = new String[lista_vehiculos.size()][10];
        for(int i=0; i<lista_vehiculos.size();i++){
            matriz[i][0]=valueOf(lista_vehiculos.get(i).getCodigo());
            matriz[i][1]=lista_vehiculos.get(i).getMarca();
            matriz[i][2]=lista_vehiculos.get(i).getLinea();
            matriz[i][3]=lista_vehiculos.get(i).getAgnio();
            matriz[i][4]=valueOf(lista_vehiculos.get(i).getValorI());

        }
        table_vehiculos.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "Código", "Marca", "Línea", "Año", "Valor"
            } 
            
        ){
            
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            };
            
        });
    }
    
    public void mostrarMarcasVehiculosComboBox(){
        String marca_p = "mas";
        for (int i=0; i<vehiculos_disponibles.size();i++) {
            if (marca_p != vehiculos_disponibles.get(i).getMarca()) {
                input_marca.addItem(vehiculos_disponibles.get(i).getMarca());
                marca_p = vehiculos_disponibles.get(i).getMarca();
            }        
        }
    }
    
    public void agregarValor(String seleccion){
        for (int i=0; i<vehiculos_disponibles.size(); i++) {
            if (seleccion.equals(vehiculos_disponibles.get(i).getAgnio())) {
                input_valor.setText(valueOf(vehiculos_disponibles.get(i).getValorI()));
            } 
        }
    }
    
    public void rellenarAutosDisponibles(){
        
        vehiculos_disponibles.add(new Vehiculo("NISSAN", "SENTRA", "1992", 1, Float.parseFloat("5000")));
        vehiculos_disponibles.add(new Vehiculo("NISSAN", "SENTRA", "1995", 2, Float.parseFloat("7000")));
        vehiculos_disponibles.add(new Vehiculo("NISSAN", "SENTRA", "2007", 3, Float.parseFloat("15000")));
        
        vehiculos_disponibles.add(new Vehiculo("CHEVROLET", "AVEO", "2002", 4, Float.parseFloat("8000")));
        vehiculos_disponibles.add(new Vehiculo("CHEVROLET", "AVEO", "2006", 5, Float.parseFloat("14000")));
        vehiculos_disponibles.add(new Vehiculo("CHEVROLET", "AVEO", "2010", 6, Float.parseFloat("18000")));
        
        vehiculos_disponibles.add(new Vehiculo("RENAULT", "LOGAN", "2004", 7, Float.parseFloat("8000")));
        vehiculos_disponibles.add(new Vehiculo("RENAULT", "LOGAN", "2010", 8, Float.parseFloat("15000")));
        vehiculos_disponibles.add(new Vehiculo("RENAULT", "LOGAN", "2015", 9, Float.parseFloat("20000")));
        
        vehiculos_disponibles.add(new Vehiculo("RENAULT", "ALASKAN", "2007", 7, Float.parseFloat("12000")));
        vehiculos_disponibles.add(new Vehiculo("RENAULT", "ALASKAN", "2012", 8, Float.parseFloat("16000")));
        vehiculos_disponibles.add(new Vehiculo("RENAULT", "ALASKAN", "2019", 9, Float.parseFloat("26000")));
        
        vehiculos_disponibles.add(new Vehiculo("RENAULT", "CAPTUR", "2008", 7, Float.parseFloat("15000")));
        vehiculos_disponibles.add(new Vehiculo("RENAULT", "CAPTUR", "2014", 8, Float.parseFloat("19000")));
        vehiculos_disponibles.add(new Vehiculo("RENAULT", "CAPTUR", "2019", 9, Float.parseFloat("28000")));
        
        vehiculos_disponibles.add(new Vehiculo("RENAULT", "ZOE", "2010", 7, Float.parseFloat("11000")));
        vehiculos_disponibles.add(new Vehiculo("RENAULT", "ZOE", "2016", 8, Float.parseFloat("13000")));
        vehiculos_disponibles.add(new Vehiculo("RENAULT", "ZOE", "2021", 9, Float.parseFloat("24000")));
        
    }
    
    public Vehiculo buscar(int codigo){//ESTE METODO LO AGREGUE PARA PODER RETORNAR EL CDIGO Y BUSCAR LA INFORMACION PERTENENCIENTE AL MISMO..HC
        for (int i = 0; i <vehiculos_disponibles.size() ; i++) {
            if(vehiculos_disponibles.get(i).getCodigo() == codigo)
                return vehiculos_disponibles.get(i);
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cambiar_desc;
    private javax.swing.JButton btn_panel_cambiar_desc;
    private javax.swing.JLabel descPPL;
    private javax.swing.JLabel descSPL;
    private javax.swing.JLabel descTCL;
    private javax.swing.JComboBox<String> input_agnio;
    private javax.swing.JTextField input_codigo;
    private javax.swing.JTextField input_descPP;
    private javax.swing.JTextField input_descSP;
    private javax.swing.JTextField input_descTC;
    private javax.swing.JComboBox<String> input_linea;
    private javax.swing.JComboBox<String> input_marca;
    private javax.swing.JLabel input_valor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_desc;
    private javax.swing.JTable table_vehiculos;
    // End of variables declaration//GEN-END:variables
}
